function init(self)
  self.collided = false
end

function on_message(self, message_id, message, sender)
  if message_id == constants.COLLISION_RESPONSE and not self.collided then
    if message.group == constants.BULLET then
      self.collided = true
      go.delete(message.other_id)
      msg.post(constants.GAME_ID, "change_game_state", { won = true })
      sprite.play_flipbook("#sprite", "reset_done")
    end
  end
end
