function update(self, dt)
  for i = -1, 1, 2 do
    msg.post("@render:", "draw_line", {start_point = vmath.vector3(-320, 80 * i, 0), end_point = vmath.vector3(320, 80 * i, 0), color = vmath.vector4(1)})
  end

  for i = 0, 3 do
    msg.post("@render:", "draw_line", {start_point = vmath.vector3(160 * i - 320, -240, 0), end_point = vmath.vector3(160 * i - 320, 240, 0), color = vmath.vector4(1)})
  end
end
